/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectocomputador;
  import javax.swing.*;

import proyectocomputador.Buses;
import proyectocomputador.CPU;
import proyectocomputador.Memoria;
import Utils.Utils;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author 57313
 */
public class Computador extends javax.swing.JPanel {

    private Buses buses;
    private CPU cpu;
    private Memoria memoria;
    private Utils utils;

    /**
     * Creates new form NewJPanel
     */
    public Computador() {
        initComponents();
        logo();
    }

    private void setScaledIcon(JLabel label, String imagePath, int width, int height) {

        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(scaledImage));
    }

    private void logo() {
        String ruta = System.getProperty("user.dir") + "\\src\\IMAGES\\";

        File testFile = new File(ruta);
        if (testFile.exists()) {
            setScaledIcon(this.ImageALU1, ruta + "ALU1.png", 80, 80);
            setScaledIcon(this.ImageALU2, ruta + "ALU2.png", 80, 80);
            return;
        }
        System.err.println("No se encontró la carpeta IMAGES");
    }

    public static void main(String[] args) {
        ProyectoComputador.main(args);
    }
    
    public class Ventana {
        public static void main(String[] args) {
            SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Computador");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(400, 300);

                // Agregar el JPanel a la ventana
                frame.add(new Computador());

                frame.setVisible(true);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMemoriaProgramas = new javax.swing.JPanel();
        ListProgramas = new java.awt.List();
        LabelMemoriaProgramas = new javax.swing.JLabel();
        PanelBusControl = new javax.swing.JPanel();
        LabelBusControl = new javax.swing.JLabel();
        FieldBusControl = new javax.swing.JTextField();
        PanelBusDirecciones = new javax.swing.JPanel();
        LabelBusDirecciones = new javax.swing.JLabel();
        FieldBusDirecciones = new javax.swing.JTextField();
        PanelBusDatos = new javax.swing.JPanel();
        LabelBusDatos = new javax.swing.JLabel();
        FieldDatos = new javax.swing.JTextField();
        PanelCPU = new javax.swing.JPanel();
        LabelMAR = new javax.swing.JLabel();
        LabelIR = new javax.swing.JLabel();
        LabelMBR = new javax.swing.JLabel();
        LabelPC = new javax.swing.JLabel();
        LabelALU1 = new javax.swing.JLabel();
        LabelUC = new javax.swing.JLabel();
        FieldUC = new javax.swing.JTextField();
        FieldIR = new javax.swing.JTextField();
        FieldMBR = new javax.swing.JTextField();
        FieldPC = new javax.swing.JTextField();
        FieldMAR = new javax.swing.JTextField();
        ImageALU1 = new javax.swing.JLabel();
        LabelRegistros = new javax.swing.JLabel();
        LabelALU2 = new javax.swing.JLabel();
        ImageALU2 = new javax.swing.JLabel();
        FieldALU1 = new javax.swing.JTextField();
        FieldALU2 = new javax.swing.JTextField();
        LabelPSW = new javax.swing.JLabel();
        FieldPSW = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableRegistros = new javax.swing.JTable();
        PanelIO = new javax.swing.JPanel();
        LabelIO = new javax.swing.JLabel();
        FieldIO = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextInstrucciones = new javax.swing.JTextArea();
        LabelInstrucciones = new javax.swing.JLabel();
        PanelProcesos = new javax.swing.JPanel();
        LabelPROCESOS = new javax.swing.JLabel();
        LabelProceso2 = new javax.swing.JTextField();
        LabelProceso3 = new javax.swing.JTextField();
        LabelProceso1 = new javax.swing.JTextField();
        PanelMemoriaDatos = new javax.swing.JPanel();
        ListDatos = new java.awt.List();
        LabelMemoriaDatos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        PanelMemoriaProgramas.setBackground(new java.awt.Color(0, 0, 0));
        PanelMemoriaProgramas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        ListProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProgramasActionPerformed(evt);
            }
        });

        LabelMemoriaProgramas.setForeground(new java.awt.Color(255, 255, 255));
        LabelMemoriaProgramas.setText("Memoria Programas");

        javax.swing.GroupLayout PanelMemoriaProgramasLayout = new javax.swing.GroupLayout(PanelMemoriaProgramas);
        PanelMemoriaProgramas.setLayout(PanelMemoriaProgramasLayout);
        PanelMemoriaProgramasLayout.setHorizontalGroup(
            PanelMemoriaProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMemoriaProgramasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelMemoriaProgramasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(LabelMemoriaProgramas)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PanelMemoriaProgramasLayout.setVerticalGroup(
            PanelMemoriaProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMemoriaProgramasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelMemoriaProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelBusControl.setBackground(new java.awt.Color(0, 0, 0));
        PanelBusControl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        LabelBusControl.setBackground(new java.awt.Color(255, 255, 255));
        LabelBusControl.setForeground(new java.awt.Color(255, 255, 255));
        LabelBusControl.setText("Bus Control");

        FieldBusControl.setBackground(new java.awt.Color(0, 0, 0));
        FieldBusControl.setForeground(new java.awt.Color(255, 255, 255));
        FieldBusControl.setText("...");

        javax.swing.GroupLayout PanelBusControlLayout = new javax.swing.GroupLayout(PanelBusControl);
        PanelBusControl.setLayout(PanelBusControlLayout);
        PanelBusControlLayout.setHorizontalGroup(
            PanelBusControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusControlLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(LabelBusControl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBusControlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(FieldBusControl)
                .addContainerGap())
        );
        PanelBusControlLayout.setVerticalGroup(
            PanelBusControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBusControl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldBusControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        PanelBusDirecciones.setBackground(new java.awt.Color(0, 0, 0));
        PanelBusDirecciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        LabelBusDirecciones.setForeground(new java.awt.Color(255, 255, 255));
        LabelBusDirecciones.setText("Bus Direcciones");

        FieldBusDirecciones.setBackground(new java.awt.Color(0, 0, 0));
        FieldBusDirecciones.setForeground(new java.awt.Color(255, 255, 255));
        FieldBusDirecciones.setText("...");

        javax.swing.GroupLayout PanelBusDireccionesLayout = new javax.swing.GroupLayout(PanelBusDirecciones);
        PanelBusDirecciones.setLayout(PanelBusDireccionesLayout);
        PanelBusDireccionesLayout.setHorizontalGroup(
            PanelBusDireccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusDireccionesLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(LabelBusDirecciones)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(PanelBusDireccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FieldBusDirecciones)
                .addContainerGap())
        );
        PanelBusDireccionesLayout.setVerticalGroup(
            PanelBusDireccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusDireccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBusDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldBusDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        PanelBusDatos.setBackground(new java.awt.Color(0, 0, 0));
        PanelBusDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        LabelBusDatos.setForeground(new java.awt.Color(255, 255, 255));
        LabelBusDatos.setText("Bus Datos");

        FieldDatos.setBackground(new java.awt.Color(0, 0, 0));
        FieldDatos.setForeground(new java.awt.Color(255, 255, 255));
        FieldDatos.setText("...");

        javax.swing.GroupLayout PanelBusDatosLayout = new javax.swing.GroupLayout(PanelBusDatos);
        PanelBusDatos.setLayout(PanelBusDatosLayout);
        PanelBusDatosLayout.setHorizontalGroup(
            PanelBusDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusDatosLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(LabelBusDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelBusDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBusDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FieldDatos)
                    .addContainerGap()))
        );
        PanelBusDatosLayout.setVerticalGroup(
            PanelBusDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBusDatos)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(PanelBusDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBusDatosLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(FieldDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        PanelCPU.setBackground(new java.awt.Color(0, 0, 0));
        PanelCPU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        PanelCPU.setForeground(new java.awt.Color(255, 255, 255));

        LabelMAR.setForeground(new java.awt.Color(255, 255, 255));
        LabelMAR.setText("MAR");

        LabelIR.setForeground(new java.awt.Color(255, 255, 255));
        LabelIR.setText("IR");

        LabelMBR.setForeground(new java.awt.Color(255, 255, 255));
        LabelMBR.setText("MBR");

        LabelPC.setForeground(new java.awt.Color(255, 255, 255));
        LabelPC.setText("PC");

        LabelALU1.setForeground(new java.awt.Color(255, 255, 255));
        LabelALU1.setText("ALU1");

        LabelUC.setForeground(new java.awt.Color(255, 255, 255));
        LabelUC.setText("UC");

        FieldUC.setBackground(new java.awt.Color(0, 0, 0));
        FieldUC.setForeground(new java.awt.Color(255, 255, 255));
        FieldUC.setText("...");

        FieldIR.setBackground(new java.awt.Color(0, 0, 0));
        FieldIR.setForeground(new java.awt.Color(255, 255, 255));
        FieldIR.setText("...");

        FieldMBR.setBackground(new java.awt.Color(0, 0, 0));
        FieldMBR.setForeground(new java.awt.Color(255, 255, 255));
        FieldMBR.setText("...");

        FieldPC.setBackground(new java.awt.Color(0, 0, 0));
        FieldPC.setForeground(new java.awt.Color(255, 255, 255));
        FieldPC.setText("...");

        FieldMAR.setBackground(new java.awt.Color(0, 0, 0));
        FieldMAR.setForeground(new java.awt.Color(255, 255, 255));
        FieldMAR.setText("...");

        ImageALU1.setForeground(new java.awt.Color(255, 255, 255));
        ImageALU1.setText(".");

        LabelRegistros.setForeground(new java.awt.Color(255, 255, 255));
        LabelRegistros.setText("Registros");

        LabelALU2.setForeground(new java.awt.Color(255, 255, 255));
        LabelALU2.setText("ALU2");

        ImageALU2.setForeground(new java.awt.Color(255, 255, 255));
        ImageALU2.setText(".");

        FieldALU1.setBackground(new java.awt.Color(0, 0, 0));
        FieldALU1.setForeground(new java.awt.Color(255, 255, 255));
        FieldALU1.setText("...");

        FieldALU2.setBackground(new java.awt.Color(0, 0, 0));
        FieldALU2.setForeground(new java.awt.Color(255, 255, 255));
        FieldALU2.setText("...");

        LabelPSW.setForeground(new java.awt.Color(255, 255, 255));
        LabelPSW.setText("PSW");

        FieldPSW.setBackground(new java.awt.Color(0, 0, 0));
        FieldPSW.setForeground(new java.awt.Color(255, 255, 255));
        FieldPSW.setText("...");

        TableRegistros.setBackground(new java.awt.Color(0, 0, 0));
        TableRegistros.setForeground(new java.awt.Color(255, 255, 255));
        TableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TableRegistros);

        javax.swing.GroupLayout PanelCPULayout = new javax.swing.GroupLayout(PanelCPU);
        PanelCPU.setLayout(PanelCPULayout);
        PanelCPULayout.setHorizontalGroup(
            PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCPULayout.createSequentialGroup()
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(LabelRegistros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCPULayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelCPULayout.createSequentialGroup()
                                .addComponent(FieldMBR, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCPULayout.createSequentialGroup()
                                .addComponent(LabelMBR)
                                .addGap(78, 78, 78))
                            .addGroup(PanelCPULayout.createSequentialGroup()
                                .addComponent(FieldMAR)
                                .addContainerGap()))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCPULayout.createSequentialGroup()
                            .addComponent(LabelMAR)
                            .addGap(78, 78, 78))
                        .addGroup(PanelCPULayout.createSequentialGroup()
                            .addComponent(FieldPC, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCPULayout.createSequentialGroup()
                        .addComponent(LabelPC)
                        .addGap(83, 83, 83))))
            .addGroup(PanelCPULayout.createSequentialGroup()
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelCPULayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FieldALU2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(FieldALU1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(PanelCPULayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelALU1))
                            .addGroup(PanelCPULayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(ImageALU2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelALU2)))
                        .addGap(124, 124, 124))
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ImageALU1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelIR)
                            .addComponent(LabelUC))
                        .addGap(83, 83, 83))
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FieldUC)
                            .addComponent(FieldIR)
                            .addComponent(FieldPSW, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCPULayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LabelPSW)
                        .addContainerGap())))
        );
        PanelCPULayout.setVerticalGroup(
            PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCPULayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(LabelIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageALU1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelALU1)
                .addGap(5, 5, 5)
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addComponent(FieldALU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelALU2)
                            .addComponent(ImageALU2))
                        .addGap(18, 18, 18)
                        .addComponent(FieldALU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCPULayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(FieldUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelUC))
                        .addGap(18, 18, 18)
                        .addComponent(LabelPSW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldPSW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PanelCPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addComponent(LabelPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(LabelMAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldMAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelMBR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FieldMBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(PanelCPULayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelRegistros)
                        .addGap(14, 14, 14))))
        );

        PanelIO.setBackground(new java.awt.Color(0, 0, 0));
        PanelIO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        LabelIO.setForeground(new java.awt.Color(255, 255, 255));
        LabelIO.setText("I/O");

        FieldIO.setBackground(new java.awt.Color(0, 0, 0));
        FieldIO.setForeground(new java.awt.Color(255, 255, 255));
        FieldIO.setText("...");
        FieldIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIOLayout = new javax.swing.GroupLayout(PanelIO);
        PanelIO.setLayout(PanelIOLayout);
        PanelIOLayout.setHorizontalGroup(
            PanelIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FieldIO)
                    .addGroup(PanelIOLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelIO)))
                .addGap(65, 65, 65))
        );
        PanelIOLayout.setVerticalGroup(
            PanelIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIOLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelIO)
                .addGap(40, 40, 40)
                .addComponent(FieldIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TextInstrucciones.setBackground(new java.awt.Color(102, 102, 102));
        TextInstrucciones.setColumns(20);
        TextInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        TextInstrucciones.setRows(5);
        TextInstrucciones.setText("SADSDLJ");
        jScrollPane2.setViewportView(TextInstrucciones);

        LabelInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        LabelInstrucciones.setText("Comando de instrucciones");

        PanelProcesos.setBackground(new java.awt.Color(0, 0, 0));
        PanelProcesos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        LabelPROCESOS.setForeground(new java.awt.Color(255, 255, 255));
        LabelPROCESOS.setText("Descripción proceso");

        LabelProceso2.setBackground(new java.awt.Color(0, 0, 0));
        LabelProceso2.setForeground(new java.awt.Color(255, 255, 255));
        LabelProceso2.setText("...");

        LabelProceso3.setBackground(new java.awt.Color(0, 0, 0));
        LabelProceso3.setForeground(new java.awt.Color(255, 255, 255));
        LabelProceso3.setText("...");

        LabelProceso1.setBackground(new java.awt.Color(0, 0, 0));
        LabelProceso1.setForeground(new java.awt.Color(255, 255, 255));
        LabelProceso1.setText("...");

        javax.swing.GroupLayout PanelProcesosLayout = new javax.swing.GroupLayout(PanelProcesos);
        PanelProcesos.setLayout(PanelProcesosLayout);
        PanelProcesosLayout.setHorizontalGroup(
            PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabelPROCESOS)
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(PanelProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelProceso2)
                    .addComponent(LabelProceso3)
                    .addComponent(LabelProceso1))
                .addContainerGap())
        );
        PanelProcesosLayout.setVerticalGroup(
            PanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPROCESOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelProceso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LabelProceso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelProceso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PanelMemoriaDatos.setBackground(new java.awt.Color(0, 0, 0));
        PanelMemoriaDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        ListDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListDatosActionPerformed(evt);
            }
        });

        LabelMemoriaDatos.setForeground(new java.awt.Color(255, 255, 255));
        LabelMemoriaDatos.setText("Memoria Datos");

        javax.swing.GroupLayout PanelMemoriaDatosLayout = new javax.swing.GroupLayout(PanelMemoriaDatos);
        PanelMemoriaDatos.setLayout(PanelMemoriaDatosLayout);
        PanelMemoriaDatosLayout.setHorizontalGroup(
            PanelMemoriaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMemoriaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelMemoriaDatosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(LabelMemoriaDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMemoriaDatosLayout.setVerticalGroup(
            PanelMemoriaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMemoriaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelMemoriaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelBusDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelBusControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelBusDirecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelMemoriaProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(LabelInstrucciones)))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(954, Short.MAX_VALUE)
                    .addComponent(PanelMemoriaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(254, 254, 254)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelBusControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PanelBusDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PanelBusDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PanelCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelProcesos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelMemoriaProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(PanelMemoriaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(364, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProgramasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListProgramasActionPerformed

    private void FieldIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIOActionPerformed

    private void ListDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldALU1;
    private javax.swing.JTextField FieldALU2;
    private javax.swing.JTextField FieldBusControl;
    private javax.swing.JTextField FieldBusDirecciones;
    private javax.swing.JTextField FieldDatos;
    private javax.swing.JTextField FieldIO;
    private javax.swing.JTextField FieldIR;
    private javax.swing.JTextField FieldMAR;
    private javax.swing.JTextField FieldMBR;
    private javax.swing.JTextField FieldPC;
    private javax.swing.JTextField FieldPSW;
    private javax.swing.JTextField FieldUC;
    private javax.swing.JLabel ImageALU1;
    private javax.swing.JLabel ImageALU2;
    private javax.swing.JLabel LabelALU1;
    private javax.swing.JLabel LabelALU2;
    private javax.swing.JLabel LabelBusControl;
    private javax.swing.JLabel LabelBusDatos;
    private javax.swing.JLabel LabelBusDirecciones;
    private javax.swing.JLabel LabelIO;
    private javax.swing.JLabel LabelIR;
    private javax.swing.JLabel LabelInstrucciones;
    private javax.swing.JLabel LabelMAR;
    private javax.swing.JLabel LabelMBR;
    private javax.swing.JLabel LabelMemoriaDatos;
    private javax.swing.JLabel LabelMemoriaProgramas;
    private javax.swing.JLabel LabelPC;
    private javax.swing.JLabel LabelPROCESOS;
    private javax.swing.JLabel LabelPSW;
    private javax.swing.JTextField LabelProceso1;
    private javax.swing.JTextField LabelProceso2;
    private javax.swing.JTextField LabelProceso3;
    private javax.swing.JLabel LabelRegistros;
    private javax.swing.JLabel LabelUC;
    private java.awt.List ListDatos;
    private java.awt.List ListProgramas;
    private javax.swing.JPanel PanelBusControl;
    private javax.swing.JPanel PanelBusDatos;
    private javax.swing.JPanel PanelBusDirecciones;
    private javax.swing.JPanel PanelCPU;
    private javax.swing.JPanel PanelIO;
    private javax.swing.JPanel PanelMemoriaDatos;
    private javax.swing.JPanel PanelMemoriaProgramas;
    private javax.swing.JPanel PanelProcesos;
    private javax.swing.JTable TableRegistros;
    private javax.swing.JTextArea TextInstrucciones;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
